\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {lstlisting}{\numberline {2.1}GPX-Datei}{9}{lstlisting.2.1}
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
